Stopped at <exception thrown>
_exception :: e = _
()
